### Send request with dynamic variables in request's body
POST http://127.0.0.1:5000/embeddingsBatch
Content-Type: application/json

{
  "ext": "",
  "docs": [
    "aaa",
    "CCC"
  ]
}


### Send request with dynamic variables in request's body
GET http://127.0.0.1:5000/embeddings?doc=你好
